import random

QUOTES: list[str] = [
    "Jeder Schritt zählt – auch der erste!",
    "Dein Körper kann fast alles – überzeuge zuerst deinen Kopf.",
    "Ein Training, das du bereust, ist das, das du ausgelassen hast.",
    "Sport ist kein Hobby – es ist eine Lebenseinstellung.",
    "Jede Einheit zählt, jeder Tag macht den Unterschied.",
    "Stärke wächst nicht im Komfort, sondern in der Überwindung.",
    "Du wirst es nicht bereuen. Aber du wirst es bereuen, wenn du es nicht tust.",
    "Der härteste Schritt ist der aus der Tür.",
    "Fortschritt ist Fortschritt, egal wie klein.",
    "Dein heutiges Training ist dein Fundament für morgen.",
    "Kein Schmerz bleibt für immer – Stolz schon.",
    "Bewegung ist Medizin für Körper und Geist.",
    "Wer aufhört, besser zu werden, hat aufgehört, gut zu sein.",
    "Das einzige schlechte Training ist das, das nicht stattgefunden hat.",
    "Ausdauer schlägt Talent, wenn Talent keine Ausdauer hat.",
    "Dein Körper ist fähiger als du denkst – gib ihm die Chance.",
    "Jeder Kilometer bringt dich deinem Ziel einen Schritt näher.",
    "Stärke kommt aus dem Überwinden dessen, was du für unmöglich hieltest.",
    "Du trainierst nicht für gestern – du trainierst für morgen.",
    "Wer sich bewegt, gewinnt – immer.",
    "Geschwindigkeit kommt mit der Zeit, Beständigkeit bringt sie.",
    "Ein starker Wille besiegt jeden Muskelkater.",
    "Disziplin ist der Weg zwischen deinen Zielen und deiner Wirklichkeit.",
    "Gemeinsam läuft es sich leichter als allein.",
    "Der Körper gibt auf, bevor der Geist es tut – lass den Geist entscheiden.",
    "Heute schwitzt du, morgen glänzt du.",
    "Sport verbindet – jede gemeinsame Runde stärkt das Team.",
    "Wer regelmäßig trainiert, investiert in sein bestes Ich.",
    "Niemals aufgeben – der nächste Schritt ist immer möglich.",
    "Dein Ruhepuls sinkt, dein Selbstvertrauen steigt.",
    "Bewegung ist die günstigste Apotheke der Welt.",
    "Stell dir vor, wie du dich nach dem Training fühlen wirst.",
    "Jede Woche, die du durchhältst, macht die nächste leichter.",
    "Nicht die Schnellen gewinnen, sondern die, die nicht aufhören.",
    "Schweiß ist Fett, das weint – mach ihm Beine.",
    "Du bist stärker als deine Ausreden.",
    "Ein kleines Workout ist besser als gar keines.",
    "Laufen klärt den Kopf wie nichts anderes.",
    "Jede Herausforderung macht dich widerstandsfähiger.",
    "Dein Körper braucht dich – und du brauchst ihn.",
    "Wer sich traut, der gewinnt – im Sport und im Leben.",
    "Halte durch, wenn es schwer wird – genau dann wächst du.",
    "Trainiere klug, lebe gesund, genieße die Früchte.",
    "Gemeinschaft gibt Kraft – zieht gemeinsam an einem Strang.",
    "Jeder Tropfen Schweiß ist eine Investition in deine Gesundheit.",
    "Dein Ziel wartet – du musst nur losgehen.",
    "Heute müde, morgen stolz.",
    "Die Straße fragt nicht, wie fit du bist – sie wartet einfach.",
    "Wer täglich eine Kleinigkeit tut, erreicht Großes.",
    "Sport ist der beste Ausgleich für einen stressigen Alltag.",
    "Jede Runde, die du drehst, bringt dich weiter.",
    "Dein bester Gegner bist du selbst – und den kannst du schlagen.",
    "Beständigkeit ist die Mutter aller Erfolge im Training.",
    "Wenn deine Beine aufgeben wollen, laufe mit dem Herzen.",
    "Wer Ziele hat, findet auch die Kraft, sie zu erreichen.",
    "Sport lehrt Geduld – und Geduld bewegt Berge.",
    "Ein Lächeln bei jedem Training macht es leichter.",
    "Dein Körper erinnert sich an jedes Training – und dankt es dir.",
    "Nichts motiviert mehr als das Gefühl nach dem Sport.",
    "Du hast die Wahl: Couch oder Laufschuhe. Wähle weise.",
    "Energie erzeugt Energie – starte, und der Rest kommt von selbst.",
    "Regelmäßigkeit ist wichtiger als Intensität.",
    "Dein Fortschritt beginnt genau da, wo deine Komfortzone endet.",
    "Sport schenkt dir Energie für alles andere im Leben.",
    "Zusammen sind wir schneller, stärker und ausdauernder.",
    "Wer heute trainiert, feiert morgen Erfolge.",
    "Mach es nicht perfekt – mach es einfach.",
    "Der erste Kilometer ist der schwerste – der letzte der schönste.",
    "Dein Trainingsplan ist deine Landkarte zum Erfolg.",
    "Kraft entsteht nicht durch leichte Aufgaben, sondern durch Überwindung.",
    "Jede Einheit bringt dich deiner Bestzeit näher.",
    "Drücke dich nicht um das Training – drück lieber Gewichte.",
    "Wer in Bewegung bleibt, bleibt jung im Geist.",
    "Fang klein an, denke groß, bleibe dran.",
    "Sport ist der direkteste Weg zu einem besseren Wohlbefinden.",
    "Leg los – der Körper folgt dem Entschluss.",
    "Tapferkeit im Training zahlt sich im Wettkampf aus.",
    "Vergleiche dich nur mit dir von gestern – und werde besser.",
    "Ein starkes Team trägt jeden Schwächeren ein Stück weit mit.",
    "Jeder Schweiß-Tropfen zählt auf dem Weg zum Ziel.",
    "Wer kämpft, kann verlieren – wer nicht kämpft, hat schon verloren.",
    "Ausdauer ist das Geheimnis aller Sieger.",
    "Nimm die Treppe – es zählt als Training.",
    "Bewegung ist das beste Geschenk, das du dir selbst machen kannst.",
    "Nutze die Zeit, die du hast, und tu das Beste daraus.",
    "Im Team wächst jeder über sich hinaus.",
    "Schweige die Zweifel und lass die Beine reden.",
    "Dein Herz ist der stärkste Muskel – trainiere ihn.",
    "Sport verbindet Menschen jeder Art und Herkunft.",
    "Wer sich regelmäßig bewegt, schläft besser, denkt klarer.",
    "Kein Ziel ist zu weit, wenn man regelmäßig losgeht.",
    "Dein Trainingspartner wartet – enttäusch ihn nicht.",
    "Jede Minute Bewegung ist ein Gewinn für deine Gesundheit.",
    "Halte dein Versprechen an dich selbst – trainiere heute.",
    "Wenn es leicht wäre, würde es jeder tun – du tust es.",
    "Schritt für Schritt, Tag für Tag – so werden Ziele erreicht.",
    "Die einzige Begrenzung bist du selbst – überschreite sie.",
    "Lauf, springe, trainiere – du bist lebendiger als je zuvor.",
    "Deine Disziplin von heute ist dein Erfolg von morgen.",
    "Wer aufhört, besser zu werden, hat aufgehört, gut zu sein.",
]


def get_random_quote() -> str:
    """Gibt einen zufälligen Motivationsspruch zurück."""
    return random.choice(QUOTES)
