"""add donation voting tables

Rein additiv/non-destruktiv (siehe 1t8s): legt nur die drei neuen Tabellen
donation_proposals, donation_polls und donation_votes samt ihrer Indizes an.
Bestehende Tabellen werden nicht angefasst (Autogenerate lief diesmal ohne
den bekannten Drift an challenges.public_id, siehe lessons-learned).

Revision ID: 1e5248e475d7
Revises: 15377314500e
Create Date: 2026-07-15 14:51:58.721010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e5248e475d7'
down_revision = '15377314500e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('donation_proposals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('challenge_id', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('donation_proposals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_donation_proposals_challenge_id'), ['challenge_id'], unique=False)

    op.create_table('donation_polls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('challenge_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('max_votes_per_user', sa.Integer(), nullable=False),
    sa.Column('winner_proposal_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['winner_proposal_id'], ['donation_proposals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('challenge_id')
    )
    op.create_table('donation_votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('proposal_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['proposal_id'], ['donation_proposals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'proposal_id')
    )
    with op.batch_alter_table('donation_votes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_donation_votes_proposal_id'), ['proposal_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donation_votes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_donation_votes_proposal_id'))

    op.drop_table('donation_votes')
    op.drop_table('donation_polls')
    with op.batch_alter_table('donation_proposals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_donation_proposals_challenge_id'))

    op.drop_table('donation_proposals')
    # ### end Alembic commands ###
