"""add approval fields to users

Revision ID: 26244f8f650b
Revises: 897dbbcea723
Create Date: 2026-04-24 16:13:00.946413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26244f8f650b'
down_revision = '897dbbcea723'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_approved', sa.Boolean(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('approved_by_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_users_approved_by_id', 'users', ['approved_by_id'], ['id'])

    # Bestehende User werden automatisch freigeschaltet, damit niemand ausgesperrt wird
    op.execute("UPDATE users SET is_approved = 1 WHERE is_approved = 0")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('fk_users_approved_by_id', type_='foreignkey')
        batch_op.drop_column('approved_by_id')
        batch_op.drop_column('approved_at')
        batch_op.drop_column('is_approved')

    # ### end Alembic commands ###
