"""add nickname to users

Revision ID: 77fe1b237497
Revises: 2307226a4e48
Create Date: 2026-04-27 13:34:01.705864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77fe1b237497'
down_revision = '2307226a4e48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nickname', sa.String(length=30), nullable=True))
        batch_op.create_unique_constraint('uq_users_nickname', ['nickname'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('uq_users_nickname', type_='unique')
        batch_op.drop_column('nickname')

    # ### end Alembic commands ###
