"""connector_credentials

Revision ID: 897dbbcea723
Revises: 3e27b32f8e92
Create Date: 2026-04-24 13:00:29.993906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '897dbbcea723'
down_revision = '3e27b32f8e92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('connector_credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider_type', sa.String(length=64), nullable=False),
    sa.Column('credentials', sa.String(length=2048), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'provider_type')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('connector_credentials')
    # ### end Alembic commands ###
