"""add reason to sick_periods and sick_period_likes

Revision ID: aab58a149773
Revises: a3f7e2b9c1d5
Create Date: 2026-06-08 12:59:11.892085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aab58a149773'
down_revision = 'a3f7e2b9c1d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sick_period_likes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sick_period_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['sick_period_id'], ['sick_periods.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sick_period_id', 'user_id', name='uq_sick_period_like_user')
    )
    with op.batch_alter_table('sick_period_likes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sick_period_likes_sick_period_id'), ['sick_period_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sick_period_likes_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('sick_periods', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reason', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sick_periods', schema=None) as batch_op:
        batch_op.drop_column('reason')

    with op.batch_alter_table('sick_period_likes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sick_period_likes_user_id'))
        batch_op.drop_index(batch_op.f('ix_sick_period_likes_sick_period_id'))

    op.drop_table('sick_period_likes')
    # ### end Alembic commands ###
