"""add activity likes and comments

Revision ID: b0fe5687f411
Revises: 72fada0b34c5
Create Date: 2026-04-29 16:02:43.859018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0fe5687f411'
down_revision = '72fada0b34c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activity_comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_comments_activity_id'), ['activity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_comments_user_id'), ['user_id'], unique=False)

    op.create_table('activity_likes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('activity_id', 'user_id', name='uq_activity_like_user')
    )
    with op.batch_alter_table('activity_likes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_likes_activity_id'), ['activity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_likes_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_likes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_likes_user_id'))
        batch_op.drop_index(batch_op.f('ix_activity_likes_activity_id'))

    op.drop_table('activity_likes')
    with op.batch_alter_table('activity_comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_comments_user_id'))
        batch_op.drop_index(batch_op.f('ix_activity_comments_activity_id'))

    op.drop_table('activity_comments')
    # ### end Alembic commands ###
